# Generated by Django 5.0.2 on 2024-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_brand',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_gender',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_size',
            field=models.IntegerField(null=True),
        ),
    ]
