# Generated by Django 5.0.2 on 2024-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_products_product_brand_products_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_qty',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_qty',
            field=models.IntegerField(null=True),
        ),
    ]
