# Generated by Django 5.0.2 on 2024-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_cart_product_id_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_amount',
            field=models.IntegerField(null=True),
        ),
    ]
