# Generated by Django 5.0.2 on 2024-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_orders_order_qty_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
