# Generated by Django 5.0.2 on 2024-03-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_products_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
