# Generated by Django 5.0.2 on 2024-03-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_product_name_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
