# Generated by Django 5.0.2 on 2024-03-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_rename_name_products_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.TextField(choices=[(1, 'processed'), (3, 'delivered'), (4, 'rejected')], default=0)),
                ('f_name', models.TextField(max_length=100, null=True)),
                ('d_address', models.TextField(max_length=300, null=True)),
                ('h_address', models.TextField(max_length=300, null=True)),
                ('city', models.TextField(max_length=100, null=True)),
                ('state', models.TextField(max_length=100, null=True)),
                ('country', models.TextField(max_length=100, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('name_of_card', models.TextField(max_length=100, null=True)),
                ('card_no', models.IntegerField(null=True)),
                ('exp_month', models.IntegerField(null=True)),
                ('exp_year', models.IntegerField(null=True)),
                ('cvv', models.TextField(max_length=100, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg')),
            ],
        ),
    ]
