# Generated by Django 5.0.2 on 2024-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='l_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
