# Generated by Django 5.0.2 on 2024-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_checkout_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amts',
            field=models.IntegerField(null=True),
        ),
    ]
