# Generated by Django 5.0.2 on 2024-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_checkout_amts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='exp_year',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='name_of_card',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cdate',
            field=models.DateField(null=True),
        ),
    ]
