# Generated by Django 5.0.2 on 2024-03-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_checkout_card_no_remove_checkout_cvv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('location', models.TextField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg')),
            ],
        ),
    ]
