# Generated by Django 5.0.2 on 2024-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='amts',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_status',
            field=models.TextField(choices=[('confirm', 'confirm'), ('processed', 'processed'), ('delivered', 'delivered'), ('rejected', 'rejected')], default='confirm'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='img',
            field=models.ImageField(null=True, upload_to='profile-image/'),
        ),
    ]
