# Generated by Django 5.0.2 on 2024-03-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_products_number_of_items_alter_checkout_amts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='img',
            field=models.ImageField(default='../static/images/01.png', null=True, upload_to='profile-image/'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg'),
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=300, null=True)),
                ('one_star_rating', models.PositiveIntegerField(default=0)),
                ('two_star_rating', models.PositiveIntegerField(default=0)),
                ('three_star_rating', models.PositiveIntegerField(default=0)),
                ('four_star_rating', models.PositiveIntegerField(default=0)),
                ('five_star_rating', models.PositiveIntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg')),
            ],
        ),
    ]
