# Generated by Django 5.0.2 on 2024-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_edit_img_alter_edit_user_id_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='taken_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
