# Generated by Django 5.0.2 on 2024-03-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_remove_rating_product_id_rating_taken_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.products'),
        ),
    ]
