# Generated by Django 5.0.2 on 2024-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_alter_products_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
