# Generated by Django 5.0.2 on 2024-03-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_rating_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='five_star_rating',
            new_name='star_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='four_star_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='one_star_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='three_star_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='two_star_rating',
        ),
    ]
