# Generated by Django 5.0.2 on 2024-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_rename_five_star_rating_rating_star_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
    ]
