# Generated by Django 5.0.2 on 2024-03-31 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg'),
        ),
    ]
