# Generated by Django 5.0.2 on 2024-04-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_wishlist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(max_length=100, null=True)),
                ('l_name', models.TextField(max_length=100, null=True)),
                ('d_address', models.TextField(max_length=300, null=True)),
                ('h_address', models.TextField(max_length=300, null=True)),
                ('city', models.TextField(max_length=100, null=True)),
                ('state', models.TextField(max_length=100, null=True)),
                ('country', models.TextField(max_length=100, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('e_mail', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user_reg')),
            ],
        ),
    ]
