# Generated by Django 5.0.2 on 2024-04-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_savedaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedaddress',
            name='product_id',
        ),
    ]
