# Generated by Django 5.0.2 on 2024-04-02 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_contact_fullname_contact_mail_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.products'),
        ),
    ]
