# Generated by Django 5.0.2 on 2024-04-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_wishlist_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='edit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.edit'),
        ),
    ]
