# Generated by Django 5.0.2 on 2024-04-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_rating_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='edit',
            new_name='edit1',
        ),
    ]
