# Generated by Django 5.0.2 on 2024-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_rename_edit_rating_edit1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='edit1',
        ),
        migrations.AddField(
            model_name='user_reg',
            name='img1',
            field=models.ImageField(default='../static/images/01.png', null=True, upload_to='profile-image/'),
        ),
    ]
