# Generated by Django 5.0.2 on 2024-04-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_alter_user_reg_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg',
            name='img1',
            field=models.ImageField(default='../static/assets/images/01.png', null=True, upload_to='profile-image/'),
        ),
    ]
